name: ASpawn
version: '1.0'
main: org.example.spawn.aSpawn.ASpawn
api-version: '1.21'
authors: [ Ardelys ]
description: 'A plugin that allows players to set their spawn points and teleport.'
commands:
  setspawn:
    description: 'It sets the spawn point.'
    usage: '/setspawn'
    permission: aspawn.setspawn
  spawn:
    description: 'You will teleport to the spawn point.'
    usage: '/spawn'
permissions:
  aspawn.setspawn:
    description: 'Permission to change the spawn point.'
    default: op